function main(){
   
    database.ref('/').update({
        z1:z1,
        z2:z2,
        z3:z3,
        z4:z4,
        z5:z5,
        z6:z6,
        z7:z7,
        z8:z8,
        z9:z9,
        x1:x1,
        x2:x2,
        x3:x3,
        x4:x4,
        x5:x5,
        x6:x6,
        x7:x7,
        x8:x8,
        x9:x9
    });
    var gameStateRef  = database.ref('z1');
        gameStateRef.on("value",function(data){
        z1 = data.val();
    });
    var gameStateRef  = database.ref('z2');
        gameStateRef.on("value",function(data){
        z2 = data.val();
        });
        var gameStateRef  = database.ref('z3');
        gameStateRef.on("value",function(data){
        z3 = data.val();
        });
        var gameStateRef  = database.ref('z4');
        gameStateRef.on("value",function(data){
        z4 = data.val();
        });
        var gameStateRef  = database.ref('z5');
        gameStateRef.on("value",function(data){
        z5 = data.val();
        });
        var gameStateRef  = database.ref('z6');
        gameStateRef.on("value",function(data){
        z6 = data.val();
        });
        var gameStateRef  = database.ref('z7');
        gameStateRef.on("value",function(data){
        z7 = data.val();
        });
        var gameStateRef  = database.ref('z8');
        gameStateRef.on("value",function(data){
        z8 = data.val();
        });
        var gameStateRef  = database.ref('z9');
        gameStateRef.on("value",function(data){
        z9 = data.val();
        });
        var gameStateRef  = database.ref('x1');
        gameStateRef.on("value",function(data){
        x1 = data.val();
        });
        var gameStateRef  = database.ref('x2');
        gameStateRef.on("value",function(data){
        x2 = data.val();
        });
        var gameStateRef  = database.ref('x3');
        gameStateRef.on("value",function(data){
        x3 = data.val();
        });
        var gameStateRef  = database.ref('x4');
        gameStateRef.on("value",function(data){
        x4 = data.val();
        });
        var gameStateRef  = database.ref('x5');
        gameStateRef.on("value",function(data){
        x5 = data.val();
        });
        var gameStateRef  = database.ref('x6');
        gameStateRef.on("value",function(data){
        x6 = data.val();
        });
        var gameStateRef  = database.ref('x7');
        gameStateRef.on("value",function(data){
        x7 = data.val();
        });
        var gameStateRef  = database.ref('x8');
        gameStateRef.on("value",function(data){
        x8 = data.val();
        });
        var gameStateRef  = database.ref('x9');
        gameStateRef.on("value",function(data){
        x9 = data.val();
        });
        database.ref('/').update({
            chance:chance
        });
        var gameStateRef  = database.ref('chance');
        gameStateRef.on("value",function(data){
        chance = data.val();
        });
    if(chance===0&&index===2){
        if(keyDown("1")&&s1.visible===false&&d1.visible===false){
            z1=1;
            chance=1;
        }
        if(keyDown("2")&&s2.visible===false&&d2.visible===false){
            z2=1;
            chance=1;
        }
        if(keyDown("3")&&s3.visible===false&&d3.visible===false){
            z3=1;
            chance=1;
        }
        if(keyDown("4")&&s4.visible===false&&d4.visible===false){
            z4=1;
            chance=1;
        }
        if(keyDown("5")&&s5.visible===false&&d5.visible===false){
            z5=1;
            chance=1;
        }
        if(keyDown("6")&&s6.visible===false&&d6.visible===false){
            z6=1;
            chance=1;
        }
        if(keyDown("7")&&s7.visible===false&&d7.visible===false){
            z7=1;
            chance=1;
        }
        if(keyDown("8")&&s8.visible===false&&d8.visible===false){
            z8=1;
            chance=1;
        }
        if(keyDown("9")&&s9.visible===false&&d9.visible===false){
            z9=1;
            chance=1;
        }
    }
    if(chance===1&&index===3){
        if(keyDown("1")&&s1.visible===false&&d1.visible===false){
            x1=1;
            chance=2;
        }
        if(keyDown("2")&&s2.visible===false&&d2.visible===false){
            x2=1;
            chance=2;
        }
        if(keyDown("3")&&s3.visible===false&&d3.visible===false){
            x3=1;
            chance=2;
        }
        if(keyDown("4")&&s4.visible===false&&d4.visible===false){
            x4=1;
            chance=2;
        }
        if(keyDown("5")&&s5.visible===false&&d5.visible===false){
            x5=1;
            chance=2;
        }
        if(keyDown("6")&&s6.visible===false&&d6.visible===false){
            x6=1;
            chance=2;
        }
        if(keyDown("7")&&s7.visible===false&&d7.visible===false){
            x7=1;
            chance=2;
        }
        if(keyDown("8")&&s8.visible===false&&d8.visible===false){
            x8=1;
            chance=2;
        }
        if(keyDown("9")&&s9.visible===false&&d9.visible===false){
            x9=1;
            chance=2;
        }
    }
    if(chance===2&&index===2){
        if(keyDown("1")&&s1.visible===false&&d1.visible===false){
            z1=1;
            chance=3;
        }
        if(keyDown("2")&&s2.visible===false&&d2.visible===false){
            z2=1;
            chance=3;
        }
        if(keyDown("3")&&s3.visible===false&&d3.visible===false){
            z3=1;
            chance=3;
        }
        if(keyDown("4")&&s4.visible===false&&d4.visible===false){
            z4=1;
            chance=3;
        }
        if(keyDown("5")&&s5.visible===false&&d5.visible===false){
            z5=1;
            chance=3;
        }
        if(keyDown("6")&&s6.visible===false&&d6.visible===false){
            z6=1;
            chance=3;
        }
        if(keyDown("7")&&s7.visible===false&&d7.visible===false){
            z7=1;
            chance=3;
        }
        if(keyDown("8")&&s8.visible===false&&d8.visible===false){
            z8=1;
            chance=3;
        }
        if(keyDown("9")&&s9.visible===false&&d9.visible===false){
            z9=1;
            chance=3;
        }
    }
    if(chance===3&&index===3){
        if(keyDown("1")&&s1.visible===false&&d1.visible===false){
            x1=1;
            chance=4;
        }
        if(keyDown("2")&&s2.visible===false&&d2.visible===false){
            x2=1;
            chance=4;
        }
        if(keyDown("3")&&s3.visible===false&&d3.visible===false){
            x3=1;
            chance=4;
        }
        if(keyDown("4")&&s4.visible===false&&d4.visible===false){
            x4=1;
            chance=4;
        }
        if(keyDown("5")&&s5.visible===false&&d5.visible===false){
            x5=1;
            chance=4;
        }
        if(keyDown("6")&&s6.visible===false&&d6.visible===false){
            x6=1;
            chance=4;
        }
        if(keyDown("7")&&s7.visible===false&&d7.visible===false){
            x7=1;
            chance=4;
        }
        if(keyDown("8")&&s8.visible===false&&d8.visible===false){
            x8=1;
            chance=4;
        }
        if(keyDown("9")&&s9.visible===false&&d9.visible===false){
            x9=1;
            chance=4;
        }
    }
    if(chance===4&&index===2){
        if(keyDown("1")&&s1.visible===false&&d1.visible===false){
            z1=1;
            chance=5;
        }
        if(keyDown("2")&&s2.visible===false&&d2.visible===false){
            z2=1;
            chance=5;
        }
        if(keyDown("3")&&s3.visible===false&&d3.visible===false){
            z3=1;
            chance=5;
        }
        if(keyDown("4")&&s4.visible===false&&d4.visible===false){
            z4=1;
            chance=5;
        }
        if(keyDown("5")&&s5.visible===false&&d5.visible===false){
            z5=1;
            chance=5;
        }
        if(keyDown("6")&&s6.visible===false&&d6.visible===false){
            z6=1;
            chance=5;
        }
        if(keyDown("7")&&s7.visible===false&&d7.visible===false){
            z7=1;
            chance=5;
        }
        if(keyDown("8")&&s8.visible===false&&d8.visible===false){
            z8=1;
            chance=5;
        }
        if(keyDown("9")&&s9.visible===false&&d9.visible===false){
            z9=1;
            chance=5;
        }
    }
    if(chance===5&&index===3){
        if(keyDown("1")&&s1.visible===false&&d1.visible===false){
            x1=1;
            chance=6;
        }
        if(keyDown("2")&&s2.visible===false&&d2.visible===false){
            x2=1;
            chance=6;
        }
        if(keyDown("3")&&s3.visible===false&&d3.visible===false){
            x3=1;
            chance=6;
        }
        if(keyDown("4")&&s4.visible===false&&d4.visible===false){
            x4=1;
            chance=6;
        }
        if(keyDown("5")&&s5.visible===false&&d5.visible===false){
            x5=1;
            chance=6;
        }
        if(keyDown("6")&&s6.visible===false&&d6.visible===false){
            x6=1;
            chance=6;
        }
        if(keyDown("7")&&s7.visible===false&&d7.visible===false){
            x7=1;
            chance=6;
        }
        if(keyDown("8")&&s8.visible===false&&d8.visible===false){
            x8=1;
            chance=6;
        }
        if(keyDown("9")&&s9.visible===false&&d9.visible===false){
            x9=1;
            chance=6;
        }
    }
    if(chance===6&&index===2){
        if(keyDown("1")&&s1.visible===false&&d1.visible===false){
            z1=1;
            chance=7;
        }
        if(keyDown("2")&&s2.visible===false&&d2.visible===false){
            z2=1;
            chance=7;
        }
        if(keyDown("3")&&s3.visible===false&&d3.visible===false){
            z3=1;
            chance=7;
        }
        if(keyDown("4")&&s4.visible===false&&d4.visible===false){
            z4=1;
            chance=7;
        }
        if(keyDown("5")&&s5.visible===false&&d5.visible===false){
            z5=1;
            chance=7;
        }
        if(keyDown("6")&&s6.visible===false&&d6.visible===false){
            z6=1;
            chance=7;
        }
        if(keyDown("7")&&s7.visible===false&&d7.visible===false){
            z7=1;
            chance=7;
        }
        if(keyDown("8")&&s8.visible===false&&d8.visible===false){
            z8=1;
            chance=7;
        }
        if(keyDown("9")&&s9.visible===false&&d9.visible===false){
            z9=1;
            chance=7;
        }
    }
    if(chance===7&&index===3){
        if(keyDown("1")&&s1.visible===false&&d1.visible===false){
            x1=1;
            chance=8;
        }
        if(keyDown("2")&&s2.visible===false&&d2.visible===false){
            x2=1;
            chance=8;
        }
        if(keyDown("3")&&s3.visible===false&&d3.visible===false){
            x3=1;
            chance=8;
        }
        if(keyDown("4")&&s4.visible===false&&d4.visible===false){
            x4=1;
            chance=8;
        }
        if(keyDown("5")&&s5.visible===false&&d5.visible===false){
            x5=1;
            chance=8;
        }
        if(keyDown("6")&&s6.visible===false&&d6.visible===false){
            x6=1;
            chance=8;
        }
        if(keyDown("7")&&s7.visible===false&&d7.visible===false){
            x7=1;
            chance=8;
        }
        if(keyDown("8")&&s8.visible===false&&d8.visible===false){
            x8=1;
            chance=8;
        }
        if(keyDown("9")&&s9.visible===false&&d9.visible===false){
            x9=1;
            chance=8;
        }
    }
    if(chance===8&&index===2){
        if(keyDown("1")&&s1.visible===false&&d1.visible===false){
            z1=1;
            chance=9;
        }
        if(keyDown("2")&&s2.visible===false&&d2.visible===false){
            z2=1;
            chance=9;
        }
        if(keyDown("3")&&s3.visible===false&&d3.visible===false){
            z3=1;
            chance=9;
        }
        if(keyDown("4")&&s4.visible===false&&d4.visible===false){
            z4=1;
            chance=9;
        }
        if(keyDown("5")&&s5.visible===false&&d5.visible===false){
            z5=1;
            chance=9;
        }
        if(keyDown("6")&&s6.visible===false&&d6.visible===false){
            z6=1;
            chance=9;
        }
        if(keyDown("7")&&s7.visible===false&&d7.visible===false){
            z7=1;
            chance=9;
        }
        if(keyDown("8")&&s8.visible===false&&d8.visible===false){
            z8=1;
            chance=9;
        }
        if(keyDown("9")&&s9.visible===false&&d9.visible===false){
            z9=1;
            chance=9;
        }
    }
    if(chance===0&&index===2){
        e1.mousePressed(()=>{
            if(s1.visible===false&&d1.visible===false){
                z1=1;
                chance=1;
            }
        });
        e2.mousePressed(()=>{
            if(s2.visible===false&&d2.visible===false){
                z2=1;
                chance=1;
            }
        });
        e3.mousePressed(()=>{
            if(s3.visible===false&&d3.visible===false){
                z3=1;
                chance=1;
            }
        });
        e4.mousePressed(()=>{
            if(s4.visible===false&&d4.visible===false){
                z4=1;
                chance=1;
            }
        });
        e5.mousePressed(()=>{
            if(s5.visible===false&&d5.visible===false){
                z5=1;
                chance=1;
            }
        });
        e6.mousePressed(()=>{
            if(s6.visible===false&&d6.visible===false){
                z6=1;
                chance=1;
            }
        });
        e7.mousePressed(()=>{
            if(s7.visible===false&&d7.visible===false){
                z7=1;
                chance=1;
            }
        });
        e8.mousePressed(()=>{
            if(s8.visible===false&&d8.visible===false){
                z8=1;
                chance=1;
            }
        });
        e9.mousePressed(()=>{
            if(s9.visible===false&&d9.visible===false){
                z9=1;
                chance=1;
            }
        });
    }
    if(chance===1&&index===3){
        e1.mousePressed(()=>{
            if(s1.visible===false&&d1.visible===false){
                x1=1;
                chance=2;
            }
        });
        e2.mousePressed(()=>{
            if(s2.visible===false&&d2.visible===false){
                x2=1;
                chance=2;
            }
        });
        e3.mousePressed(()=>{
            if(s3.visible===false&&d3.visible===false){
                x3=1;
                chance=2;
            }
        });
        e4.mousePressed(()=>{
            if(s4.visible===false&&d4.visible===false){
                x4=1;
                chance=2;
            }
        });
        e5.mousePressed(()=>{
            if(s5.visible===false&&d5.visible===false){
                x5=1;
                chance=2;
            }
        });
        e6.mousePressed(()=>{
            if(s6.visible===false&&d6.visible===false){
                x6=1;
                chance=2;
            }
        });
        e7.mousePressed(()=>{
            if(s7.visible===false&&d7.visible===false){
                x7=1;
                chance=2;
            }
        });
        e8.mousePressed(()=>{
            if(s8.visible===false&&d8.visible===false){
                x8=1;
                chance=2;
            }
        });
        e9.mousePressed(()=>{
            if(s9.visible===false&&d9.visible===false){
                x9=1;
                chance=2;
            }
        });
    }
    if(chance===2&&index===2){
        e1.mousePressed(()=>{
            if(s1.visible===false&&d1.visible===false){
                z1=1;
                chance=3;
            }
        });
        e2.mousePressed(()=>{
            if(s2.visible===false&&d2.visible===false){
                z2=1;
                chance=3;
            }
        });
        e3.mousePressed(()=>{
            if(s3.visible===false&&d3.visible===false){
                z3=1;
                chance=3;
            }
        });
        e4.mousePressed(()=>{
            if(s4.visible===false&&d4.visible===false){
                z4=1;
                chance=3;
            }
        });
        e5.mousePressed(()=>{
            if(s5.visible===false&&d5.visible===false){
                z5=1;
                chance=3;
            }
        });
        e6.mousePressed(()=>{
            if(s6.visible===false&&d6.visible===false){
                z6=1;
                chance=3;
            }
        });
        e7.mousePressed(()=>{
            if(s7.visible===false&&d7.visible===false){
                z7=1;
                chance=3;
            }
        });
        e8.mousePressed(()=>{
            if(s8.visible===false&&d8.visible===false){
                z8=1;
                chance=3;
            }
        });
        e9.mousePressed(()=>{
            if(s9.visible===false&&d9.visible===false){
                z9=1;
                chance=3;
            }
        });
    }
    if(chance===3&&index===3){
        e1.mousePressed(()=>{
            if(s1.visible===false&&d1.visible===false){
                x1=1;
                chance=4;
            }
        });
        e2.mousePressed(()=>{
            if(s2.visible===false&&d2.visible===false){
                x2=1;
                chance=4;
            }
        });
        e3.mousePressed(()=>{
            if(s3.visible===false&&d3.visible===false){
                x3=1;
                chance=4;
            }
        });
        e4.mousePressed(()=>{
            if(s4.visible===false&&d4.visible===false){
                x4=1;
                chance=4;
            }
        });
        e5.mousePressed(()=>{
            if(s5.visible===false&&d5.visible===false){
                x5=1;
                chance=4;
            }
        });
        e6.mousePressed(()=>{
            if(s6.visible===false&&d6.visible===false){
                x6=1;
                chance=4;
            }
        });
        e7.mousePressed(()=>{
            if(s7.visible===false&&d7.visible===false){
                x7=1;
                chance=4;
            }
        });
        e8.mousePressed(()=>{
            if(s8.visible===false&&d8.visible===false){
                x8=1;
                chance=4;
            }
        });
        e9.mousePressed(()=>{
            if(s9.visible===false&&d9.visible===false){
                x9=1;
                chance=4;
            }
        });
    }
    if(chance===4&&index===2){
        e1.mousePressed(()=>{
            if(s1.visible===false&&d1.visible===false){
                z1=1;
                chance=5;
            }
        });
        e2.mousePressed(()=>{
            if(s2.visible===false&&d2.visible===false){
                z2=1;
                chance=5;
            }
        });
        e3.mousePressed(()=>{
            if(s3.visible===false&&d3.visible===false){
                z3=1;
                chance=5;
            }
        });
        e4.mousePressed(()=>{
            if(s4.visible===false&&d4.visible===false){
                z4=1;
                chance=5;
            }
        });
        e5.mousePressed(()=>{
            if(s5.visible===false&&d5.visible===false){
                z5=1;
                chance=5;
            }
        });
        e6.mousePressed(()=>{
            if(s6.visible===false&&d6.visible===false){
                z6=1;
                chance=5;
            }
        });
        e7.mousePressed(()=>{
            if(s7.visible===false&&d7.visible===false){
                z7=1;
                chance=5;
            }
        });
        e8.mousePressed(()=>{
            if(s8.visible===false&&d8.visible===false){
                z8=1;
                chance=5;
            }
        });
        e9.mousePressed(()=>{
            if(s9.visible===false&&d9.visible===false){
                z9=1;
                chance=5;
            }
        });
    }
    if(chance===5&&index===3){
        e1.mousePressed(()=>{
            if(s1.visible===false&&d1.visible===false){
                x1=1;
                chance=6;
            }
        });
        e2.mousePressed(()=>{
            if(s2.visible===false&&d2.visible===false){
                x2=1;
                chance=6;
            }
        });
        e3.mousePressed(()=>{
            if(s3.visible===false&&d3.visible===false){
                x3=1;
                chance=6;
            }
        });
        e4.mousePressed(()=>{
            if(s4.visible===false&&d4.visible===false){
                x4=1;
                chance=6;
            }
        });
        e5.mousePressed(()=>{
            if(s5.visible===false&&d5.visible===false){
                x5=1;
                chance=6;
            }
        });
        e6.mousePressed(()=>{
            if(s6.visible===false&&d6.visible===false){
                x6=1;
                chance=6;
            }
        });
        e7.mousePressed(()=>{
            if(s7.visible===false&&d7.visible===false){
                x7=1;
                chance=6;
            }
        });
        e8.mousePressed(()=>{
            if(s8.visible===false&&d8.visible===false){
                x8=1;
                chance=6;
            }
        });
        e9.mousePressed(()=>{
            if(s9.visible===false&&d9.visible===false){
                x9=1;
                chance=6;
            }
        });
    }
    if(chance===6&&index===2){
        e1.mousePressed(()=>{
            if(s1.visible===false&&d1.visible===false){
                z1=1;
                chance=7;
            }
        });
        e2.mousePressed(()=>{
            if(s2.visible===false&&d2.visible===false){
                z2=1;
                chance=7;
            }
        });
        e3.mousePressed(()=>{
            if(s3.visible===false&&d3.visible===false){
                z3=1;
                chance=7;
            }
        });
        e4.mousePressed(()=>{
            if(s4.visible===false&&d4.visible===false){
                z4=1;
                chance=7;
            }
        });
        e5.mousePressed(()=>{
            if(s5.visible===false&&d5.visible===false){
                z5=1;
                chance=7;
            }
        });
        e6.mousePressed(()=>{
            if(s6.visible===false&&d6.visible===false){
                z6=1;
                chance=7;
            }
        });
        e7.mousePressed(()=>{
            if(s7.visible===false&&d7.visible===false){
                z7=1;
                chance=7;
            }
        });
        e8.mousePressed(()=>{
            if(s8.visible===false&&d8.visible===false){
                z8=1;
                chance=7;
            }
        });
        e9.mousePressed(()=>{
            if(s9.visible===false&&d9.visible===false){
                z9=1;
                chance=7;
            }
        });
    }
    if(chance===7&&index===3){
        e1.mousePressed(()=>{
            if(s1.visible===false&&d1.visible===false){
                x1=1;
                chance=8;
            }
        });
        e2.mousePressed(()=>{
            if(s2.visible===false&&d2.visible===false){
                x2=1;
                chance=8;
            }
        });
        e3.mousePressed(()=>{
            if(s3.visible===false&&d3.visible===false){
                x3=1;
                chance=8;
            }
        });
        e4.mousePressed(()=>{
            if(s4.visible===false&&d4.visible===false){
                x4=1;
                chance=8;
            }
        });
        e5.mousePressed(()=>{
            if(s5.visible===false&&d5.visible===false){
                x5=1;
                chance=8;
            }
        });
        e6.mousePressed(()=>{
            if(s6.visible===false&&d6.visible===false){
                x6=1;
                chance=8;
            }
        });
        e7.mousePressed(()=>{
            if(s7.visible===false&&d7.visible===false){
                x7=1;
                chance=8;
            }
        });
        e8.mousePressed(()=>{
            if(s8.visible===false&&d8.visible===false){
                x8=1;
                chance=8;
            }
        });
        e9.mousePressed(()=>{
            if(s9.visible===false&&d9.visible===false){
                x9=1;
                chance=8;
            }
        });
    }
    if(chance===8&&index===2){
        e1.mousePressed(()=>{
            if(s1.visible===false&&d1.visible===false){
                z1=1;
                chance=9;
            }
        });
        e2.mousePressed(()=>{
            if(s2.visible===false&&d2.visible===false){
                z2=1;
                chance=9;
            }
        });
        e3.mousePressed(()=>{
            if(s3.visible===false&&d3.visible===false){
                z3=1;
                chance=9;
            }
        });
        e4.mousePressed(()=>{
            if(s4.visible===false&&d4.visible===false){
                z4=1;
                chance=9;
            }
        });
        e5.mousePressed(()=>{
            if(s5.visible===false&&d5.visible===false){
                z5=1;
                chance=9;
            }
        });
        e6.mousePressed(()=>{
            if(s6.visible===false&&d6.visible===false){
                z6=1;
                chance=9;
            }
        });
        e7.mousePressed(()=>{
            if(s7.visible===false&&d7.visible===false){
                z7=1;
                chance=9;
            }
        });
        e8.mousePressed(()=>{
            if(s8.visible===false&&d8.visible===false){
                z8=1;
                chance=9;
            }
        });
        e9.mousePressed(()=>{
            if(s9.visible===false&&d9.visible===false){
                z9=1;
                chance=9;
            }
        });
    }
}