function main1(){
    if(z1===1){
        s1.visible=true;
    }
    if(z2===1){
        s2.visible=true;
    }
    if(z3===1){
        s3.visible=true;
    }
    if(z4===1){
        s4.visible=true;
    }
    if(z5===1){
        s5.visible=true;
    }
    if(z6===1){
        s6.visible=true;
    }
    if(z7===1){
        s7.visible=true;
    }
    if(z8===1){
        s8.visible=true;
    }
    if(z9===1){
        s9.visible=true;
    }
    if(x1===1){
        d1.visible=true;
    }
    if(x2===1){
        d2.visible=true;
    }
    if(x3===1){
        d3.visible=true;
    }
    if(x4===1){
        d4.visible=true;
    }
    if(x5===1){
        d5.visible=true;
    }
    if(x6===1){
        d6.visible=true;
    }
    if(x7===1){
        d7.visible=true;
    }
    if(x8===1){
        d8.visible=true;
    }
    if(x9===1){
        d9.visible=true;
    }
}